version: '3.8'

services:
  app:
    build: .
    container_name: steam_knives_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_DATABASE: steam_knives
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
    volumes:
      - .:/var/www/html
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: steam_knives_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: steam_knives
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: steam_knives_redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
